# ARITHMETIC OPERATIONS

In [2]:
import numpy as np
import cv2 as cv

In [3]:
x = np.uint8([230])
y = np.uint8([80])

In [4]:
np.add(x,y)

array([54], dtype=uint8)

In [5]:
cv.add(x,y)

array([[255]], dtype=uint8)

## IMAGE BLENDING

In [24]:
img1 = cv.imread("images/Dahyun.jpg")
img2 = cv.imread("images/mina.jpg")
img3 = cv.imread("images/DahyunBlue.jpg")

In [25]:
alpha = 0.7

In [35]:
new_img = cv.addWeighted(img1, 0.3, img3, 0.7, 0)

In [36]:
cv.imshow("Dahyun", img1)
cv.imshow("Dahyun2", new_img)
cv.waitKey(0)
cv.destroyAllWindows()

## BITWISE OPERATION

In [64]:
# Load two images
img1 = cv.imread('images/Dahyun.jpg')
img2 = cv.imread('images/ReljodImg.jpg')
# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols ]
# Now create a mask of logo and create its inverse mask also
img2gray = cv.cvtColor(img2,cv.COLOR_BGR2GRAY)
ret, mask = cv.threshold(img2gray, 10, 255, cv.THRESH_BINARY)
mask_inv = cv.bitwise_not(mask)
# Now black-out the area of logo in ROI
img1_bg = cv.bitwise_and(roi,roi,mask = mask_inv)
#img1_bg = cv.bitwise_and(roi,mask_inv)
# Take only region of logo from logo image.
img2_fg = cv.bitwise_and(img2,img2,mask = mask)
#img2_fg = cv.bitwise_and(img2,mask)
# Put logo in ROI and modify the main image
dst = cv.add(img1_bg,img2_fg)
img1[0:rows, 0:cols ] = dst
cv.imshow('res',img1)
cv.waitKey(0)
cv.destroyAllWindows()

In [51]:
cv.bitwise_and(x,y)

array([[64]], dtype=uint8)

In [65]:
cv.useOptimized()

True

# PERFORMANCE MEASUREMENT AND IMPROVEMENT TECHNIQUES

In [69]:
e1 = cv.getTickCount()
for i in range(10000000):
    pass
e2 = cv.getTickCount()
time = (e2 - e1)/ cv.getTickFrequency()
print(time)

0.8120277868009851


In [71]:
img1 = cv.imread('images/Dahyun.jpg')
e1 = cv.getTickCount()
for i in range(5,49,2):
    img1 = cv.medianBlur(img1,i)
e2 = cv.getTickCount()
t = (e2 - e1)/cv.getTickFrequency()
print( t )
# Result I got is 0.521107655 seconds

9.121782578692956


In [87]:
%timeit res = cv.medianBlur(img1,49)
#res = cv.medianBlur(img1,49)

767 ms ± 3.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [88]:
cv.setUseOptimized(False)

In [89]:
cv.useOptimized()

False

In [90]:
%timeit res = cv.medianBlur(img1,49)
#res = cv.medianBlur(img1,49)

206 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
